1) PLAYERS STATS

In [4]:
from creating_datasets import get_players_stats
import pandas as pd

In [5]:
df_players = get_players_stats("2020")
df_players.head()

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]
/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

,Player,Age,Team,Pos,G,GS,MP_avg,FG,FGA,FG%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,0.444,...,14.2,36.3,9.9,3.2,13.1,0.254,8.1,1.6,9.6,7.3
1,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,0.455,...,11.4,34.4,4.5,0.6,5.1,0.118,5.3,-2.4,2.9,2.5
2,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,0.463,...,11.0,30.3,10.9,0.7,11.6,0.225,8.3,-0.9,7.5,5.9
3,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,0.437,...,16.2,34.9,5.3,0.6,5.9,0.133,6.2,-2.3,3.9,3.1
4,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,0.553,...,13.2,37.5,6.1,5.0,11.1,0.279,7.4,4.1,11.5,6.6

In [ ]:
df_players.to_csv("csv/players_stats_preview.csv", index=False)

In [6]:
df_players.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP_avg', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'MP_total', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM',
       'DBPM', 'BPM', 'VORP'],
      dtype='object')

2) TEAMS STATS

In [1]:
from creating_datasets import get_teams_stats

In [2]:
df_teams = get_teams_stats("2020")
df_teams.head()

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

,Team,W,L,MOV,SOS,SRS,ORtg,DRtg,NRtg,Pace,...,3PAr,TS%,Offense Four Factors eFG%,Offense Four Factors TOV%,Offense Four Factors ORB%,Offense Four Factors FT/FGA,Defense Four Factors eFG%,Defense Four Factors TOV%,Defense Four Factors DRB%,Defense Four Factors FT/FGA
0,Milwaukee Bucks*,56.0,17.0,10.08,-0.67,9.41,112.4,102.9,9.5,105.1,...,0.428,0.583,0.552,12.9,20.7,0.201,0.489,12.0,81.6,0.178
1,Boston Celtics*,48.0,24.0,6.31,-0.47,5.83,113.3,107.0,6.3,99.5,...,0.386,0.570,0.531,12.2,23.9,0.207,0.509,13.5,77.4,0.215
2,Los Angeles Clippers*,49.0,23.0,6.44,0.21,6.66,113.9,107.6,6.3,101.5,...,0.375,0.577,0.535,12.6,23.5,0.233,0.506,12.2,77.6,0.206
3,Toronto Raptors*,53.0,19.0,6.24,-0.26,5.97,111.1,105.0,6.1,100.9,...,0.421,0.574,0.536,13.1,21.3,0.210,0.502,14.6,76.7,0.202
4,Los Angeles Lakers*,52.0,19.0,5.79,0.49,6.28,112.0,106.3,5.7,100.9,...,0.358,0.573,0.542,13.3,24.5,0.201,0.515,14.1,78.8,0.205

In [3]:
df_teams.columns

Index(['Team', 'W', 'L', 'MOV', 'SOS', 'SRS', 'ORtg', 'DRtg', 'NRtg', 'Pace',
       'FTr', '3PAr', 'TS%', 'Offense Four Factors eFG%',
       'Offense Four Factors TOV%', 'Offense Four Factors ORB%',
       'Offense Four Factors FT/FGA', 'Defense Four Factors eFG%',
       'Defense Four Factors TOV%', 'Defense Four Factors DRB%',
       'Defense Four Factors FT/FGA'],
      dtype='object')

3) Players awards - player of the week, month, rookie of the month

In [1]:
from creating_datasets import get_award_counts

In [2]:
df_awards = get_award_counts("2020")
df_awards.iloc[:].sort_values("potw_count", ascending=False)

                   Player  potw_count  potm_count  rookie_of_month_count
15  Giannis Antetokounmpo           4           3                      0
10           Lebron James           3           2                      0
12         Damian Lillard           2           0                      0
3           Pascal Siakam           2           0                      0
17           Jaylen Brown           2           0                      0
1           Anthony Davis           2           0                      0
28           James Harden           2           1                      0
9             Luka Dončić           1           1                      0
6            Jayson Tatum           1           1                      0
7           Demar Derozan           1           0                      0
11      Spencer Dinwiddie           1           0                      0
5         Dennis Schröder           1           0                      0
4              Trae Young           1           0                      0
2      Karl-Anthony Towns           1           0                      0
21          Norman Powell           1           0                      0
22        Josh Richardson           1           0                      0
8            Nikola Jokić           1           0                      0
14        Carmelo Anthony           1           0                      0
18            Ben Simmons           1           0                      0
19          Kawhi Leonard           1           0                      0
20         Nikola Vučević           1           0                      0
16         Brandon Ingram           1           0                      0
25             Kyle Lowry           1           0                      0
26           Jimmy Butler           1           0                      0
24            Bam Adebayo           1           0                      0
23     Kristaps Porziņģis           1           0                      0
13              Ja Morant           0           0                      3
0              Coby White           0           0                      1
27          Kendrick Nunn           0           0                      3
29        Zion Williamson           0           0                      1

In [3]:
df_awards.columns

Index(['Player', 'potw_count', 'potm_count', 'rookie_of_month_count'], dtype='object')

4) Identify rookie players

In [6]:
from creating_datasets import get_rookie_players

In [7]:
df_rookies = get_rookie_players("2020")
df_rookies.head()

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

                     Player
0            Kyle Alexander
1  Nickeil Alexander-Walker
2                RJ Barrett
3             Darius Bazley
4              Goga Bitadze

In [9]:
df_rookies = get_rookie_players("2020")
df_players["is_rookie"] = df_players["Player"].isin(df_rookies["Player"])   
df_players.head()

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

,Player,Age,Team,Pos,G,GS,MP_avg,FG,FGA,FG%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,is_rookie
0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,0.444,...,36.3,9.9,3.2,13.1,0.254,8.1,1.6,9.6,7.3,False
1,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,0.455,...,34.4,4.5,0.6,5.1,0.118,5.3,-2.4,2.9,2.5,False
2,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,0.463,...,30.3,10.9,0.7,11.6,0.225,8.3,-0.9,7.5,5.9,False
3,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,0.437,...,34.9,5.3,0.6,5.9,0.133,6.2,-2.3,3.9,3.1,False
4,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,0.553,...,37.5,6.1,5.0,11.1,0.279,7.4,4.1,11.5,6.6,False

In [10]:
df_players.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP_avg', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'MP_total', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM',
       'DBPM', 'BPM', 'VORP', 'is_rookie'],
      dtype='object')

5) Creating target dataset

In [1]:
from creating_target_data import build_awards_column, get_all_nba_team, get_all_rookie_team

Typ nagrody | Wartość 
All-NBA 1st Team | 1
All-NBA 2nd Team | 2
All-NBA 3rd Team | 3
All-Rookie 1st Team | 4
All-Rookie 2nd Team | 5

In [2]:
df_all_nba = get_all_nba_team("2020")
df_all_rookie = get_all_rookie_team("2020")


df_awards = build_awards_column(df_all_nba, df_all_rookie)
print(df_awards.head(25))

                   Player  target
0   Giannis Antetokounmpo       1
1           Anthony Davis       1
2             Luka Dončić       1
3            James Harden       1
4            LeBron James       1
5            Nikola Jokić       2
6           Kawhi Leonard       2
7          Damian Lillard       2
8              Chris Paul       2
9           Pascal Siakam       2
10           Jimmy Butler       3
11            Rudy Gobert       3
12            Ben Simmons       3
13           Jayson Tatum       3
14      Russell Westbrook       3
15         Brandon Clarke       4
16              Ja Morant       4
17          Kendrick Nunn       4
18          Eric Paschall       4
19        Zion Williamson       4
20          Terence Davis       5
21          Rui Hachimura       5
22            Tyler Herro       5
23        P.J. Washington       5
24             Coby White       5