1) PLAYERS STATS

In [ ]:
from .creating_datasets import get_players_stats
import pandas as pd

In [3]:
df_players = get_players_stats("2020")
df_players.head(21)

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:25: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]
/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:25: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

,Player,Age,Team,Pos,G,GS,MP_avg,FG,FGA,FG%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,0.444,...,14.2,36.3,9.9,3.2,13.1,0.254,8.1,1.6,9.6,7.3
1,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,0.455,...,11.4,34.4,4.5,0.6,5.1,0.118,5.3,-2.4,2.9,2.5
2,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,0.463,...,11.0,30.3,10.9,0.7,11.6,0.225,8.3,-0.9,7.5,5.9
3,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,0.437,...,16.2,34.9,5.3,0.6,5.9,0.133,6.2,-2.3,3.9,3.1
4,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,0.553,...,13.2,37.5,6.1,5.0,11.1,0.279,7.4,4.1,11.5,6.6
5,Luka Dončić,20.0,DAL,PG,61.0,61.0,33.6,9.5,20.6,0.463,...,14.8,36.8,6.5,2.3,8.8,0.207,7.4,1.0,8.4,5.4
6,Kyrie Irving,27.0,BRK,PG,20.0,20.0,32.9,10.0,20.8,0.478,...,10.1,32.6,2.1,0.8,2.9,0.210,6.7,0.9,7.7,1.6
7,Russell Westbrook,31.0,HOU,PG,57.0,57.0,35.9,10.6,22.5,0.472,...,15.0,34.4,1.7,2.5,4.2,0.098,1.6,-0.1,1.5,1.8
8,Kawhi Leonard,28.0,LAC,SF,57.0,57.0,32.4,9.3,19.9,0.470,...,10.2,33.0,5.4,3.3,8.7,0.226,6.5,2.4,8.9,5.1
9,Devin Booker,23.0,PHO,SG,70.0,70.0,35.9,9.0,18.3,0.489,...,14.9,30.0,6.0,1.5,7.5,0.143,3.4,-1.3,2.2,2.6
10,Karl-Anthony Towns,24.0,MIN,C,35.0,35.0,33.9,9.0,17.8,0.508,...,13.2,28.8,3.7,1.3,5.1,0.204,7.0,0.8,7.8,2.9
11,Anthony Davis,26.0,LAL,PF,62.0,62.0,34.4,8.9,17.7,0.503,...,10.4,29.3,6.7,4.4,11.1,0.250,5.4,2.6,8.0,5.4
12,Zach LaVine,24.0,CHI,SF,60.0,60.0,34.8,9.0,20.0,0.450,...,13.3,31.7,1.8,2.2,4.0,0.091,3.3,-0.8,2.5,2.4
13,LeBron James,35.0,LAL,PG,67.0,67.0,34.6,9.6,19.4,0.493,...,15.1,31.5,6.2,3.6,9.8,0.204,6.6,1.8,8.4,6.1
14,Donovan Mitchell,23.0,UTA,SG,69.0,69.0,34.3,8.7,19.4,0.449,...,11.0,30.8,3.2,2.2,5.4,0.110,2.4,-0.6,1.9,2.3
15,Brandon Ingram,22.0,NOP,PF,62.0,62.0,33.9,8.2,17.7,0.463,...,13.1,28.1,3.3,1.8,5.1,0.115,2.5,-0.4,2.1,2.2
16,Jayson Tatum,21.0,BOS,PF,66.0,66.0,34.3,8.4,18.6,0.450,...,10.2,28.6,3.2,3.7,6.9,0.146,3.5,0.6,4.0,3.4
17,D'Angelo Russell,23.0,2TM,PG,45.0,45.0,32.3,8.0,18.8,0.426,...,13.6,31.5,1.1,0.7,1.8,0.060,3.8,-1.9,1.9,1.4
18,D'Angelo Russell,23.0,GSW,PG,33.0,33.0,32.1,8.3,19.2,0.430,...,12.6,32.2,0.9,0.4,1.3,0.058,4.5,-1.9,2.6,1.2
19,D'Angelo Russell,23.0,MIN,PG,12.0,12.0,32.7,7.3,17.6,0.412,...,16.4,29.5,0.2,0.3,0.5,0.064,1.8,-1.7,0.1,0.2
20,Joel Embiid,25.0,PHI,C,51.0,51.0,29.5,7.5,15.7,0.477,...,13.8,32.9,3.3,2.7,6.0,0.192,3.7,1.0,4.7,2.5

In [5]:
df_players.to_csv("csv/players_stats_preview.csv", index=False)

In [80]:
df_players.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP_avg', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'MP_total', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM',
       'DBPM', 'BPM', 'VORP'],
      dtype='object')

In [4]:
len(df_players.iloc[:])

651

2) TEAMS STATS

In [ ]:
from .creating_datasets import get_teams_stats

In [8]:
df_teams = get_teams_stats("2020")
df_teams.head()

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:25: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

,Team,W,L,MOV,SOS,SRS,ORtg,DRtg,NRtg,Pace,...,3PAr,TS%,Offense Four Factors eFG%,Offense Four Factors TOV%,Offense Four Factors ORB%,Offense Four Factors FT/FGA,Defense Four Factors eFG%,Defense Four Factors TOV%,Defense Four Factors DRB%,Defense Four Factors FT/FGA
0,MIL,56.0,17.0,10.08,-0.67,9.41,112.4,102.9,9.5,105.1,...,0.428,0.583,0.552,12.9,20.7,0.201,0.489,12.0,81.6,0.178
1,BOS,48.0,24.0,6.31,-0.47,5.83,113.3,107.0,6.3,99.5,...,0.386,0.570,0.531,12.2,23.9,0.207,0.509,13.5,77.4,0.215
2,LAC,49.0,23.0,6.44,0.21,6.66,113.9,107.6,6.3,101.5,...,0.375,0.577,0.535,12.6,23.5,0.233,0.506,12.2,77.6,0.206
3,TOR,53.0,19.0,6.24,-0.26,5.97,111.1,105.0,6.1,100.9,...,0.421,0.574,0.536,13.1,21.3,0.210,0.502,14.6,76.7,0.202
4,LAL,52.0,19.0,5.79,0.49,6.28,112.0,106.3,5.7,100.9,...,0.358,0.573,0.542,13.3,24.5,0.201,0.515,14.1,78.8,0.205

In [3]:
df_teams.columns

Index(['Team', 'W', 'L', 'MOV', 'SOS', 'SRS', 'ORtg', 'DRtg', 'NRtg', 'Pace',
       'FTr', '3PAr', 'TS%', 'Offense Four Factors eFG%',
       'Offense Four Factors TOV%', 'Offense Four Factors ORB%',
       'Offense Four Factors FT/FGA', 'Defense Four Factors eFG%',
       'Defense Four Factors TOV%', 'Defense Four Factors DRB%',
       'Defense Four Factors FT/FGA'],
      dtype='object')

In [3]:
print("Drużyny (pełne nazwy) w df_team_stats:")
print(df_teams["Team"])

Drużyny (pełne nazwy) w df_team_stats:
0     MIL
1     BOS
2     LAC
3     TOR
4     LAL
5     DAL
6     MIA
7     HOU
8     UTA
9     PHI
10    DEN
11    IND
12    OKC
13    PHO
14    BRK
15    ORL
16    SAS
17    MEM
18    POR
19    NOP
20    SAC
21    CHI
22    DET
23    MIN
24    WAS
25    NYK
26    CHO
27    ATL
28    CLE
29    GSW
Name: Team, dtype: object

In [4]:
df_teams.to_csv("csv/teams_stats_preview.csv", index=False)

3) Players_stats + Teams_stats, normal mean when player played in couple of teams during season

In [17]:
def resolve_multi_team_simple_average(df_players, df_team_stats, verbose=True):
    """
    Liczy prostą średnią (nieważoną) statystyk drużynowych dla graczy z 2TM/3TM itd.
    """
    import numpy as np
    import pandas as pd

    df_players["Team"] = df_players["Team"].astype(str)
    resolved_rows = []
    team_stats_cols = df_team_stats.columns.drop("Team")
    league_averages = df_team_stats[team_stats_cols].mean()
    i = 0

    for player, group in df_players.groupby("Player"):
        #print(f"Gracz '{player}'")
        #print(group)

        multi_team_row = group[group["Team"].str.match(r"^\d+TM$")]
        #print(multi_team_row)
        single_team_rows = group[~group["Team"].str.match(r"^\d+TM$")]
        #print("===" * 20)

        # if player == "Ty Jerome":
        #     print(multi_team_row)
        #     print(len(single_team_rows))

        if not multi_team_row.empty:
            i += 1
            i += 1 * len(single_team_rows)
            if single_team_rows.empty:
                if verbose:
                    print(f"⚠️ Gracz '{player}' ma '{multi_team_row.iloc[0]['Team']}', ale brak szczegółowych drużyn — pozostawiam bez zmian.")
                resolved_rows.append(multi_team_row.iloc[0])
                continue

            row = multi_team_row.iloc[0].copy()

            for stat in team_stats_cols:
                stat_values = []

                for _, g_row in single_team_rows.iterrows():
                    #print(g_row)
                    team = g_row["Team"]
                    team_info = df_team_stats[df_team_stats["Team"] == team]

                    if team_info.empty:
                        if verbose:
                            print(f"⚠️ Brak danych drużyny '{team}' dla gracza '{player}'")
                        continue

                    stat_value = team_info[stat].values[0]
                    #print(team_info[stat])
                    #print(f"Gracz '{player}' ({team}) - '{stat}': {stat_value}")
                    if not pd.isna(stat_value):
                        stat_values.append(stat_value)

                #print(stat_values)
                if stat_values:
                    row[stat] = np.mean(stat_values)  # zwykła średnia
                else:
                    row[stat] = league_averages[stat]

            resolved_rows.append(row)
        else:
            for _, single_row in single_team_rows.iterrows():
                single_row = single_row.copy()
                team = single_row["Team"]
                team_info = df_team_stats[df_team_stats["Team"] == team]
                
                if not team_info.empty:
                    for stat in team_stats_cols:
                        if pd.isna(single_row.get(stat)):
                            single_row[stat] = team_info.iloc[0][stat]
                else:
                    if verbose:
                        print(f"⚠️ Brak danych drużyny '{team}' dla gracza '{player}'")
        
                resolved_rows.append(single_row)
    
    print(i)
    
    return pd.DataFrame(resolved_rows).reset_index(drop=True)

In [18]:
# Jeśli chcesz średnią ważoną:
df_players_cleaned = resolve_multi_team_simple_average(df_players, df_teams)

182

In [62]:
df_players_cleaned.head(21)

,Player,Age,Team,Pos,G,GS,MP_avg,FG,FGA,FG%,...,NRtg,Pace,Offense Four Factors eFG%,Offense Four Factors TOV%,Offense Four Factors ORB%,Offense Four Factors FT/FGA,Defense Four Factors eFG%,Defense Four Factors TOV%,Defense Four Factors DRB%,Defense Four Factors FT/FGA
0,Aaron Gordon,24.0,ORL,PF,62.0,62.0,32.5,5.4,12.4,0.437,...,-1.00,98.60,0.5060,11.50,22.30,0.1980,0.5350,13.20,79.10,0.1760
1,Aaron Holiday,23.0,IND,PG,66.0,33.0,24.5,3.5,8.5,0.414,...,2.00,98.90,0.5340,12.00,20.00,0.1700,0.5110,13.00,76.70,0.1920
2,Abdel Nader,26.0,OKC,SF,55.0,6.0,15.8,2.2,4.8,0.468,...,2.00,98.80,0.5300,12.40,19.30,0.2310,0.5180,12.60,76.80,0.1730
3,Adam Mokoka,21.0,CHI,SF,11.0,0.0,10.2,1.1,2.5,0.429,...,-3.10,99.70,0.5150,13.70,22.80,0.1750,0.5460,16.30,75.60,0.2390
4,Admiral Schofield,22.0,WAS,PF,33.0,2.0,11.2,1.1,2.8,0.380,...,-4.60,102.70,0.5230,12.20,22.20,0.2130,0.5580,13.90,75.30,0.2310
5,Al Horford,33.0,PHI,C,67.0,61.0,30.2,4.8,10.6,0.450,...,2.30,99.00,0.5340,12.70,23.90,0.1930,0.5230,12.50,80.30,0.2140
6,Al-Farouq Aminu,29.0,ORL,PF,18.0,2.0,21.1,1.4,4.8,0.291,...,-1.00,98.60,0.5060,11.50,22.30,0.1980,0.5350,13.20,79.10,0.1760
7,Alec Burks,28.0,2TM,SF,66.0,19.0,26.6,4.9,11.6,0.418,...,-3.15,99.65,0.5155,12.95,22.70,0.2025,0.5380,13.10,78.35,0.2035
8,Al-Farouq Aminu,29.0,ORL,PF,18.0,2.0,21.1,1.4,4.8,0.291,...,-1.00,98.60,0.5060,11.50,22.30,0.1980,0.5350,13.20,79.10,0.1760
9,Alen Smailagić,19.0,GSW,C,14.0,0.0,9.9,1.4,2.9,0.500,...,-8.60,100.30,0.4970,13.20,21.50,0.2120,0.5530,13.70,76.40,0.1930
10,Alex Caruso,25.0,LAL,PG,64.0,2.0,18.4,1.9,4.5,0.412,...,5.70,100.90,0.5420,13.30,24.50,0.2010,0.5150,14.10,78.80,0.2050
11,Alex Len,26.0,2TM,C,55.0,12.0,17.6,3.2,5.8,0.555,...,-4.80,100.95,0.5245,13.40,21.75,0.1905,0.5430,13.15,76.65,0.2290
12,Alex Caruso,25.0,LAL,PG,64.0,2.0,18.4,1.9,4.5,0.412,...,5.70,100.90,0.5420,13.30,24.50,0.2010,0.5150,14.10,78.80,0.2050
13,Alfonzo McKinnie,27.0,CLE,SF,40.0,1.0,14.8,1.8,4.3,0.427,...,-7.90,98.70,0.5220,14.60,24.60,0.1720,0.5600,11.70,77.40,0.1640
14,Alize Johnson,23.0,IND,PF,17.0,1.0,6.9,0.7,1.7,0.414,...,2.00,98.90,0.5340,12.00,20.00,0.1700,0.5110,13.00,76.70,0.1920
15,Allen Crabbe,27.0,2TM,SG,37.0,1.0,17.6,1.7,4.8,0.356,...,-5.85,103.20,0.5145,13.40,21.85,0.2065,0.5420,12.95,76.05,0.2255
16,Alize Johnson,23.0,IND,PF,17.0,1.0,6.9,0.7,1.7,0.414,...,2.00,98.90,0.5340,12.00,20.00,0.1700,0.5110,13.00,76.70,0.1920
17,Allonzo Trier,24.0,NYK,SG,24.0,1.0,12.1,2.1,4.4,0.481,...,-6.50,98.60,0.5010,12.60,25.80,0.1820,0.5410,12.40,78.30,0.2240
18,Amile Jefferson,26.0,ORL,PF,18.0,0.0,4.1,0.3,0.8,0.357,...,-1.00,98.60,0.5060,11.50,22.30,0.1980,0.5350,13.20,79.10,0.1760
19,Amir Coffey,22.0,LAC,SG,18.0,1.0,8.8,1.3,3.0,0.426,...,6.30,101.50,0.5350,12.60,23.50,0.2330,0.5060,12.20,77.60,0.2060
20,Andre Drummond,26.0,2TM,C,57.0,56.0,33.0,7.3,13.8,0.533,...,-5.80,98.15,0.5255,14.20,23.60,0.1830,0.5505,12.20,76.65,0.1750

In [ ]:
duplicated = df_players_cleaned.groupby(["Player", "Team"]).size()
duplicated = duplicated[duplicated > 1]  # tylko te, które występują więcej niż raz
print(duplicated)

Series([], dtype: int64)

In [11]:
df_players_cleaned.drop_duplicates(subset=["Player", "Team"], inplace=True)

In [20]:
print(len(df_players_cleaned), "graczy w sezonie")

529 graczy w sezonie

In [15]:
df_players_cleaned.to_csv("csv/players_stats_cleaned.csv", index=False)

4) Players awards - player of the week, month, rookie of the month

In [ ]:
from .creating_datasets import get_award_counts

In [2]:
df_awards = get_award_counts("2020")
df_awards.iloc[:].sort_values("potw_count", ascending=False)

                   Player  potw_count  potm_count  rookie_of_month_count
15  Giannis Antetokounmpo           4           3                      0
10           Lebron James           3           2                      0
12         Damian Lillard           2           0                      0
3           Pascal Siakam           2           0                      0
17           Jaylen Brown           2           0                      0
1           Anthony Davis           2           0                      0
28           James Harden           2           1                      0
9             Luka Dončić           1           1                      0
6            Jayson Tatum           1           1                      0
7           Demar Derozan           1           0                      0
11      Spencer Dinwiddie           1           0                      0
5         Dennis Schröder           1           0                      0
4              Trae Young           1           0                      0
2      Karl-Anthony Towns           1           0                      0
21          Norman Powell           1           0                      0
22        Josh Richardson           1           0                      0
8            Nikola Jokić           1           0                      0
14        Carmelo Anthony           1           0                      0
18            Ben Simmons           1           0                      0
19          Kawhi Leonard           1           0                      0
20         Nikola Vučević           1           0                      0
16         Brandon Ingram           1           0                      0
25             Kyle Lowry           1           0                      0
26           Jimmy Butler           1           0                      0
24            Bam Adebayo           1           0                      0
23     Kristaps Porziņģis           1           0                      0
13              Ja Morant           0           0                      3
0              Coby White           0           0                      1
27          Kendrick Nunn           0           0                      3
29        Zion Williamson           0           0                      1

In [3]:
df_awards.columns

Index(['Player', 'potw_count', 'potm_count', 'rookie_of_month_count'], dtype='object')

5) Identify rookie players

In [ ]:
from .creating_datasets import get_rookie_players

In [7]:
df_rookies = get_rookie_players("2020")
df_rookies.head()

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

                     Player
0            Kyle Alexander
1  Nickeil Alexander-Walker
2                RJ Barrett
3             Darius Bazley
4              Goga Bitadze

In [9]:
df_rookies = get_rookie_players("2020")
df_players["is_rookie"] = df_players["Player"].isin(df_rookies["Player"])   
df_players.head()

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

,Player,Age,Team,Pos,G,GS,MP_avg,FG,FGA,FG%,...,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,is_rookie
0,James Harden,30.0,HOU,SG,68.0,68.0,36.5,9.9,22.3,0.444,...,36.3,9.9,3.2,13.1,0.254,8.1,1.6,9.6,7.3,False
1,Bradley Beal,26.0,WAS,SG,57.0,57.0,36.0,10.4,22.9,0.455,...,34.4,4.5,0.6,5.1,0.118,5.3,-2.4,2.9,2.5,False
2,Damian Lillard,29.0,POR,PG,66.0,66.0,37.5,9.5,20.4,0.463,...,30.3,10.9,0.7,11.6,0.225,8.3,-0.9,7.5,5.9,False
3,Trae Young,21.0,ATL,PG,60.0,60.0,35.3,9.1,20.8,0.437,...,34.9,5.3,0.6,5.9,0.133,6.2,-2.3,3.9,3.1,False
4,Giannis Antetokounmpo,25.0,MIL,PF,63.0,63.0,30.4,10.9,19.7,0.553,...,37.5,6.1,5.0,11.1,0.279,7.4,4.1,11.5,6.6,False

In [10]:
df_players.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP_avg', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'MP_total', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM',
       'DBPM', 'BPM', 'VORP', 'is_rookie'],
      dtype='object')

6) Creating target dataset

In [ ]:
from .creating_target_data import build_awards_column, get_all_nba_team, get_all_rookie_team

Typ nagrody | Wartość 
All-NBA 1st Team | 1
All-NBA 2nd Team | 2
All-NBA 3rd Team | 3
All-Rookie 1st Team | 4
All-Rookie 2nd Team | 5

In [2]:
df_all_nba = get_all_nba_team("2020")
df_all_rookie = get_all_rookie_team("2020")


df_awards = build_awards_column(df_all_nba, df_all_rookie)
print(df_awards.head(25))

                   Player  target
0   Giannis Antetokounmpo       1
1           Anthony Davis       1
2             Luka Dončić       1
3            James Harden       1
4            LeBron James       1
5            Nikola Jokić       2
6           Kawhi Leonard       2
7          Damian Lillard       2
8              Chris Paul       2
9           Pascal Siakam       2
10           Jimmy Butler       3
11            Rudy Gobert       3
12            Ben Simmons       3
13           Jayson Tatum       3
14      Russell Westbrook       3
15         Brandon Clarke       4
16              Ja Morant       4
17          Kendrick Nunn       4
18          Eric Paschall       4
19        Zion Williamson       4
20          Terence Davis       5
21          Rui Hachimura       5
22            Tyler Herro       5
23        P.J. Washington       5
24             Coby White       5

7) Creating full dataset

In [ ]:
from .creating_df_full import build_full_dataset

In [ ]:
X, y, df_full = build_full_dataset(last_season=2020, n_seasons=1, return_full=True)
df_full.head(5)

📦 Przetwarzanie sezonu 2020...

/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:25: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]
/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:25: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]
/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:25: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]
/home/mateusz/VScode/PROJECT-NBA_Awards_Prediction/get_table_by_id.py:25: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  return pd.read_html(str(table))[0]

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP_avg', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'MP_total', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM',
       'DBPM', 'BPM', 'VORP', 'W', 'L', 'MOV', 'SOS', 'SRS', 'ORtg', 'DRtg',
       'NRtg', 'Pace', 'Offense Four Factors eFG%',
       'Offense Four Factors TOV%', 'Offense Four Factors ORB%',
       'Offense Four Factors FT/FGA', 'Defense Four Factors eFG%',
       'Defense Four Factors TOV%', 'Defense Four Factors DRB%',
       'Defense Four Factors FT/FGA', 'potw_count', 'potm_count',
       'rookie_of_month_count', 'is_rookie', 'target'],
      dtype='object')
Cleaned data 2020

              Player   Age Team  ... is_rookie  target  season
0       Aaron Gordon  24.0  ORL  ...         0       0    2020
1      Aaron Holiday  23.0  IND  ...         0       0    2020
2        Abdel Nader  26.0  OKC  ...         0       0    2020
3        Adam Mokoka  21.0  CHI  ...         1       0    2020
4  Admiral Schofield  22.0  WAS  ...         1       0    2020

[5 rows x 73 columns]

In [3]:
df_full.to_csv("csv/stats_full.csv", index=False)

In [4]:
df_full.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP_avg', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'MP_total', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM',
       'DBPM', 'BPM', 'VORP', 'W', 'L', 'MOV', 'SOS', 'SRS', 'ORtg', 'DRtg',
       'NRtg', 'Pace', 'Offense Four Factors eFG%',
       'Offense Four Factors TOV%', 'Offense Four Factors ORB%',
       'Offense Four Factors FT/FGA', 'Defense Four Factors eFG%',
       'Defense Four Factors TOV%', 'Defense Four Factors DRB%',
       'Defense Four Factors FT/FGA', 'potw_count', 'potm_count',
       'rookie_of_month_count', 'is_rookie', 'target', 'season'],
      dtype='object')

In [5]:
df_full.isna().sum()

Player                   0
Age                      0
Team                     0
Pos                      0
G                        0
                        ..
potm_count               0
rookie_of_month_count    0
is_rookie                0
target                   0
season                   0
Length: 73, dtype: int64

In [6]:
df_full.describe()

              Age           G          GS  ...   is_rookie      target  season
count  529.000000  529.000000  529.000000  ...  529.000000  529.000000   529.0
mean    25.563327   42.330813   20.018904  ...    0.223062    0.141777  2020.0
std      4.118079   22.633322   24.238548  ...    0.416694    0.707598     0.0
min     19.000000    1.000000    0.000000  ...    0.000000    0.000000  2020.0
25%     22.000000   22.000000    0.000000  ...    0.000000    0.000000  2020.0
50%     25.000000   48.000000    6.000000  ...    0.000000    0.000000  2020.0
75%     28.000000   62.000000   39.000000  ...    0.000000    0.000000  2020.0
max     43.000000   74.000000   73.000000  ...    1.000000    5.000000  2020.0

[8 rows x 70 columns]

In [8]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529 entries, 0 to 528
Data columns (total 73 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Player                       529 non-null    object
 1   Age                          529 non-null    float64
 2   Team                         529 non-null    object
 3   Pos                          529 non-null    object
 4   G                            529 non-null    float64
 5   GS                           529 non-null    float64
 6   MP_avg                       529 non-null    float64
 7   FG                           529 non-null    float64
 8   FGA                          529 non-null    float64
 9   FG%                          529 non-null    float64
 10  3P                           529 non-null    float64
 11  3PA                          529 non-null    float64
 12  3P%                          529 non-null    float64
 13  2P                           529 non-null    float64
 14  2PA                          529 non-null    float64
 15  2P%                          529 non-null    float64
 16  eFG%                         529 non-null    float64
 17  FT                           529 non-null    float64
 18  FTA                          529 non-null    float64
 19  FT%                          529 non-null    float64
 20  ORB                          529 non-null    float64
 21  DRB                          529 non-null    float64
 22  TRB                          529 non-null    float64
 23  AST                          529 non-null    float64
 24  STL                          529 non-null    float64
 25  BLK                          529 non-null    float64
 26  TOV                          529 non-null    float64
 27  PF                           529 non-null    float64
 28  PTS                          529 non-null    float64
 29  MP_total                     529 non-null    float64
 30  PER                          529 non-null    float64
 31  TS%                          529 non-null    float64
 32  3PAr                         529 non-null    float64
 33  FTr                          529 non-null    float64
 34  ORB%                         529 non-null    float64
 35  DRB%                         529 non-null    float64
 36  TRB%                         529 non-null    float64
 37  AST%                         529 non-null    float64
 38  STL%                         529 non-null    float64
 39  BLK%                         529 non-null    float64
 40  TOV%                         529 non-null    float64
 41  USG%                         529 non-null    float64
 42  OWS                          529 non-null    float64
 43  DWS                          529 non-null    float64
 44  WS                           529 non-null    float64
 45  WS/48                        529 non-null    float64
 46  OBPM                         529 non-null    float64
 47  DBPM                         529 non-null    float64
 48  BPM                          529 non-null    float64
 49  VORP                         529 non-null    float64
 50  W                            529 non-null    float64
 51  L                            529 non-null    float64
 52  MOV                          529 non-null    float64
 53  SOS                          529 non-null    float64
 54  SRS                          529 non-null    float64
 55  ORtg                         529 non-null    float64
 56  DRtg                         529 non-null    float64
 57  NRtg                         529 non-null    float64
 58  Pace                         529 non-null    float64
 59  Offense Four Factors eFG%    529 non-null    float64
 60  Offense Four Factors TOV%    529 non-null    float64
 61  Offense Four Factors ORB%    529 non-null    float64
 62  Offense Four Factors FT/FGA  529 non-null    float64
 63  Defense Four Factors eFG%    529 non-null    float64
 64  Defense Four Factors TOV%    529 non-null    float64
 65  Defense Four Factors DRB%    529 non-null    float64
 66  Defense Four Factors FT/FGA  529 non-null    float64
 67  potw_count                   529 non-null    int64
 68  potm_count                   529 non-null    int64
 69  rookie_of_month_count        529 non-null    int64
 70  is_rookie                    529 non-null    int64
 71  target                       529 non-null    int64
 72  season                       529 non-null    int64
dtypes: float64(64), int64(6), object(3)
memory usage: 301.8+ KB